name: Latest blog post workflow
on:
  workflow_dispatch:
jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/blog-post-workflow@master
        id: blog-post-workflow
        with:
          feed_list: "https://medium.com/feed/@vishalqw78"
          max_post_count: 2
          output_only: true
      - run: echo  ${{ steps.blog-post-workflow.outputs.results }}
