name: Latest stack overflow activity
on:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *'
permissions:
  contents: write
jobs:
  update-readme-with-blog:
    name: Update this repo's README with the latest activity from StackOverflow
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Get StackOverflow activity
        id: stackoverflow_activity
        uses: gautamkrishnar/blog-post-workflow@v1
        with:
          comment_tag_name: "STACKOVERFLOW"
          feed_list: "https://medium.com/feed/@vishalqw78"
      - name: Calculate counter
        id: calculate_counter
        echo "{counter}={$(( ${{ steps.stackoverflow_activity.outputs.counter }} - 1 ))}" >> $GITHUB_OUTPUT
      - name: Update README
        run: |
          echo "<tr><td>${{ steps.stackoverflow_activity.outputs.title }}</td><td>${{ steps.stackoverflow_activity.outputs.url }}</td><td>${{ $GITHUB_OUTPUT }}</td></tr>" >> README.md
