name: Latest Stack Overflow activity 2
on:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *'
permissions:
  contents: write
jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest activity from StackOverflow
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Get StackOverflow activity
        id: get_blog_post
        uses: gautamkrishnar/blog-post-workflow@v1
        with:
          comment_tag_name: "STACKOVERFLOW"
          feed_list: "https://medium.com/feed/@username"
          template: |
            <tr>
              <td>${{ steps.get_blog_post.outputs.results.title }}</td>
              <td>${{ steps.get_blog_post.outputs.results.url }}</td>
              <td>${{ steps.get_blog_post.outputs.results.counter }}</td>
            </tr>
      - name: Calculate and update the counter value
        run: echo "::set-output name=updated_counter::$(( ${{ steps.get_blog_post.outputs.results.counter }} - 1 ))"
        id: update_counter
      - name: Print Power Value
        run: echo "The power value is ${{ steps.update_counter.outputs.results.updated_counter }}"
