name: Update README and Iterate Valu

on:
  push:
    branches:
      - main

jobs:
  update_readme_and_iterate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Git
        run: |
          git config --global user.name "vishalqw78"
          git config --global user.email "vishalpalqw78@gmail.com"

      - name: Update README and Iterate Value
        run: |
          max_value=10

          for i in $(seq 0 $max_value); do
            sed -i "s/VALUE_TO_UPDATE/$i/" README.md
            git add README.md
            git commit -m "Update README with value: $i"
          done

      - name: Push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.TOEKEN }}
